### ISSUE TITLE
Just in case you're not aware...

### ISSUE THREAD

**Issue by Venryx** [zzish/react-latex#4]
There is this very similar React wrapper project (which also uses katex under-the-hood) here: https://github.com/talyssonoc/react-katex

**Comment by blaiprat** [comment]
Thanks @Venryx! We were using this react component inside our project because at that time there wasn't anything out there that could be used inside React. The alternative was Mathquill, but that was manipulating the DOM once it was rendered and it's hard to contol within react.

Later we decided to extract the module to be reusable across our projects and leave it out there for everyone. At the point we published we weren't aware of react-katex.

We are aware that some parts of our module are not standard, and at some point we'd like to improve them, but so far we haven't had the bandwidth to improve our implementation to be more open.
